---
title: weconomy
author: decentralising the future
email: jmaviveiros@gmail.com
description: ''
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope: ''
  values: ''
- scope: ''
  values: ''
plugins:
- jekyll-feed
- jekyll-menus
